# Generated by Django 2.2.5 on 2019-10-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='bio',
            field=models.TextField(max_length=100),
        ),
    ]
