# Generated by Django 2.2.5 on 2019-10-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditclone', '0002_auto_20191001_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
