# Generated by Django 2.2.5 on 2019-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditclone', '0002_auto_20191004_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='bio',
            field=models.TextField(max_length=200),
        ),
    ]
