# Generated by Django 2.2.5 on 2019-10-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditclone', '0002_auto_20191003_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
    ]
