# Generated by Django 2.2.5 on 2019-10-04 01:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redditclone', '0003_auto_20191003_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redditclone.Comment'),
        ),
    ]
